### ISSUE TITLE
"prefix"

### ISSUE THREAD

**Issue by ghost** [superkhau/lice#18]

**Comment by superkhau** [comment]
@stokebreakup Why do you want to prefix the files with `license` or `tos`?

**Comment by superkhau** [comment]
@stokebreakup Yep, sounds fine with one suggestion. Instead of prefixing, we could just add a type identifier to other license types as a suffix before the extension. For example:

```
mpl-2.0.txt // already exists, leave it alone in this format
facebook.tos.txt // new type with .tos for a terms of service type
```
