### ISSUE TITLE
update release?

### ISSUE THREAD

**Issue by stokebreakup** [superkhau/lice#20]
please there aren’t any releases here.  can we update v.1.0.28 to 1.2.0 (https://github.com/superkhau/lice/tags)?
[I was confused because package.json was updated but the area called 'releases' still didn't include the latest update. And I don't know how to contribute or update this.]

**Comment by ralyodio** [comment]
@superkhau think we need another release

**Comment by superkhau** [comment]
<img width="331" alt="image" src="https://github.com/superkhau/lice/assets/1617364/dc8277eb-4a26-4d54-9042-ba6f0577510e">
