### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [superkhau/lice#8]
Hello everyone.

I would like to know if this project is active. There are 2 pull-requests that were not merged into main/master in this open source repository. Is this project active?

I'm thinking of initially adding 3 open source licenses here. But one question: can I add proprietary licenses here, or should it only be open licenses?

**Comment by ralyodio** [comment]
Talk to @superkhau but I believe its intent is Open Source licenses. however I don't see a problem with adding others.

**Comment by superkhau** [comment]
Yes, just merged both PRs. 

>can I add proprietary licenses here, or should it only be open licenses?

I don't see a problem either. Feel free to open a PR and we can go into details there.

**Comment by superkhau** [comment]
Closing as resolved.
